### ISSUE TITLE
tcanny not found when replace r9 dll with r10

### ISSUE THREAD

**Issue by fuchanghao** [HomeOfVapourSynthEvolution/VapourSynth-TCanny#4]
vapoursynth r38 offcial build.
l-smash works r929
vsedit r16

the vscode for example:

dbmasklight = core.tcanny.TCanny(aaed,sigma=0.6,t_h=8.0,planes=0,op=2)
dbmaskdark = core.tcanny.TCanny(aaed,sigma=0.4,t_h=7.0,planes=0,op=2)

it reports:

Python exception: No attribute with the name tcanny exists. Did you mistype a plugin namespace?

**Comment by HolyWu** [comment]
Open the dll with `Dependency Walker` and see whether it finds OpenCL.dll.
