### ISSUE TITLE
Plugin it not loaded on non opencl machine (bis)

### ISSUE THREAD

**Issue by Ichunjo** [HomeOfVapourSynthEvolution/VapourSynth-TCanny#7]
Hello, it's me again.

I tried again to compile with meson and checked with `Dependency Walker` since I've seen what you wrote in https://github.com/HomeOfVapourSynthEvolution/VapourSynth-TCanny/issues/4#issuecomment-320390551.
There seems to be a lot of missing dependencies and I don't know why.

Anyway could you provide a non-opencl dll like you did for EEDI3, please?

Thanks in advance!

**Comment by HolyWu** [comment]
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-TCanny/releases/download/r12/TCanny-r12_non-OpenCL.7z

**Comment by Ichunjo** [comment]
Many thanks!
